config/routes.rb
Rails.application.routes.draw do
  root "announcements#index"
  get "auth/:provider/callback", to: "sessions#googleAuth"
  get "auth/failure", to: redirect("/")
  resources :announcements
  resources :leaderboards
  resources :users
  resources :activities
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/leaderboard.rb
class Leaderboard < ApplicationRecord
end

app/controllers/leaderboards_controller.rb
class LeaderboardsController < ApplicationController
  before_action :set_leaderboard, only: %i[ show edit update destroy ]

  # GET /leaderboards or /leaderboards.json
  def index
    @leaderboards = Leaderboard.all
  end

  # GET /leaderboards/1 or /leaderboards/1.json
  def show
  end

  # GET /leaderboards/new
  def new
    @leaderboard = Leaderboard.new
  end

  # GET /leaderboards/1/edit
  def edit
  end

  # POST /leaderboards or /leaderboards.json
  def create
    @leaderboard = Leaderboard.new(leaderboard_params)

    respond_to do |format|
      if @leaderboard.save
        format.html { redirect_to leaderboard_url(@leaderboard), notice: "Leaderboard was successfully created." }
        format.json { render :show, status: :created, location: @leaderboard }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @leaderboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leaderboards/1 or /leaderboards/1.json
  def update
    respond_to do |format|
      if @leaderboard.update(leaderboard_params)
        format.html { redirect_to leaderboard_url(@leaderboard), notice: "Leaderboard was successfully updated." }
        format.json { render :show, status: :ok, location: @leaderboard }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @leaderboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leaderboards/1 or /leaderboards/1.json
  def destroy
    @leaderboard.destroy

    respond_to do |format|
      format.html { redirect_to leaderboards_url, notice: "Leaderboard was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_leaderboard
      @leaderboard = Leaderboard.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def leaderboard_params
      params.require(:leaderboard).permit(:description, :deadline, :start_date, :end_date)
    end
end

app/helpers/leaderboards_helper.rb
module LeaderboardsHelper
end

app/views/leaderboards/_form.html.erb
<%= form_with(model: leaderboard, class: "contents") do |form| %>
  <% if leaderboard.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(leaderboard.errors.count, "error") %> prohibited this leaderboard from being saved:</h2>

      <ul>
        <% leaderboard.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :deadline %>
    <%= form.check_box :deadline, class: "block mt-2 h-5 w-5" %>
  </div>

  <div class="my-5">
    <%= form.label :start_date %>
    <%= form.text_field :start_date, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :end_date %>
    <%= form.text_field :end_date, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/leaderboards/_leaderboard.html.erb
<div id="<%= dom_id leaderboard %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= leaderboard.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Deadline:</strong>
    <%= leaderboard.deadline %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Start date:</strong>
    <%= leaderboard.start_date %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">End date:</strong>
    <%= leaderboard.end_date %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this leaderboard", leaderboard, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this leaderboard', edit_leaderboard_path(leaderboard), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/leaderboards/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing leaderboard</h1>

  <%= render "form", leaderboard: @leaderboard %>

  <%= link_to "Show this leaderboard", @leaderboard, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to leaderboards", leaderboards_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/leaderboards/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Leaderboards</h1>
    <%= link_to 'New leaderboard', new_leaderboard_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="leaderboards" class="min-w-full">
    <%= render @leaderboards %>
  </div>
</div>

app/views/leaderboards/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New leaderboard</h1>

  <%= render "form", leaderboard: @leaderboard %>

  <%= link_to 'Back to leaderboards', leaderboards_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/leaderboards/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @leaderboard %>

    <%= link_to 'Edit this leaderboard', edit_leaderboard_path(@leaderboard), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this leaderboard', leaderboard_path(@leaderboard), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to leaderboards', leaderboards_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>